spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSl=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10485760 # 上传文件大小限定为10M
      max-request-size: 10485760

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

server:
  port: 8080
# 驼峰下划线转换
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名()
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)