# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.test.boot.fi.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# 可以省略
basic:
  enable: true
  username: admin
  password: 123456