spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_ymy?useUnicode=true&characterEncoding=UTF-8&useSSl=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

logging:
  level:
    root: info
    top.test.boot.log.controller: debug
  file:
    path: D:\ideaCode\spring-boot-learning\spring-boot-log\src\main\resources\log
    name: D:\ideaCode\spring-boot-learning\spring-boot-log\src\main\resources\log\spring-boot-logs.log
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'