spring:
  data:
    redis:
      port: 6379 # Redis 端口
      host: 127.0.0.1 # Redis 服务器地址
      database: 0 # 第几个数据库(默认为0)
      password: # Redis 服务器的连接密码,默认为 空
      Lettuce:
        pool:
          min-idle: 10 # 连接池中的最小空闲连接,默认为8
          max-idle: 20 # 连接池中的最大空闲连接,默认为 0
          max-active: 100 # 连接池的最大连接数,默认为 8

#短信发送配置
ymy:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018f047971c06b0d
      accountToken: 7c41ed64a7734ad0b18e585dd1f53692
      AppID: 2c94811c8cd4da0a018f047973396b14
      templateId: 1