server:
  port: 8888

family:
  family-name: "happy family"
  father: "Jack"
  mother: "Jenny"
  child: "Tom"
  years: 6

person:
  name: zhangfei
  age: 20
  happy: false
  birthday: 2001/07/01
  maps: { k1:v1,k2:v2 }
  lists:
    - code
    - girl
    - music
  dog:
    name: 虎子
    age: 11
